### Afficher tous les livres
GET https://booknest-backend-z9vo.onrender.com/livres

### Afficher un livre par ID
GET https://booknest-backend-z9vo.onrender.com/livres/1

### Afficher tout les catégories de livres
GET https://booknest-backend-z9vo.onrender.com/livres/categories

### Afficher une catégorie de livre
GET https://booknest-backend-z9vo.onrender.com/livres/categories/Roman


###
GET https://booknest-backend-z9vo.onrender.com/livres/3/contenu/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sZSI6InV0aWxpc2F0ZXVyIiwiaWF0IjoxNzQ2MzAwMTc1LCJleHAiOjE3NDYzMDczNzV9.-sjMysaFidhphqj7yY3iTy3XFvjWJd1DT9PokZAWKRg

### Rechercher un livre par son titre
GET https://booknest-backend-z9vo.onrender.com/livres/search?titre=La Peste